name: proselint

on:
  # Trigger the workflow on push or pull requests, but only for the
  # main branch
  push:
    branches:
    - main
    - '*/ci'
  pull_request:
    branches:
    - main

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install prereqs
      run: sudo apt-get install python3-proselint

    # config file help: https://github.com/amperser/proselint/
    - name: store proselint config
      run: |
        {
          echo '{'
          echo '   "checks": {'
          echo '     "typography.diacritical_marks": false,'
          echo '     "typography.symbols": false,'
          echo '     "annotations.misc": false'
          echo '   }'
          echo '}'
        } > $HOME/.proselintrc

    - name: check prose
      run: make proselint
